name: Build Library

on:
  push:
    branches:
      - main  # or the branch you want to build on
  pull_request:
    branches:
      - main  # or the branch you want to build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # or the version of Node.js you are using

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # ensure this script is defined in your package.json

    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: built-library
        path: dist/  # path to your build output directory