name: Build Library

on:
  push:
    branches:
      - main  # or the branch you want to build on
  pull_request:
    branches:
      - main  # or the branch you want to build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Bun
      uses: oven-sh/bun-action@v1
      with:
        bun-version: 'latest'  # or specify a specific version of Bun

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build  # ensure this script is defined in your package.json

    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: built-library
        path: dist/  # path to your build output directory
